'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''
t1=0
t2=1
sum=0
while(True):
    t3=t2+t1
    print(t3)
    t1=t2
    t2=t3
    if(t3%2==0):
        sum=sum+t3
        print("sum:",sum)
    if t3>=4000000:
        break
